apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ls
spec:
  workspaces:
    - name: source
  steps:
    # Add an extra step to list the contents of /workspace
    # You might add this before or after another Task
    - name: ls
      image: alpine
      command:
        - /bin/sh
      args:
        - '-c'
        - |
          set -ex
          find /workspace
      resources: {}