apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tutorial-pipeline-
spec:
  pipelineRef:
    name: github-pipeline-deploy
  params:
    - name: gitRepository
      value: "https://github.com/thindexed/echo.git"
  workspaces:
    - name: kubeconfig
      secret:
         secretName: kubeconfig
    - name: myworkspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
