apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
  namespace: cicd
spec:
  description: >-
    This task can be used to run npm goals on a project.

    This task can be used to run npm goals on a project
    where package.json is present and has some pre-defined
    npm scripts.
  workspaces:
    - name: source
  params:
    - name: PATH
      type: string
      default: "src/web"
      description: The path where package.json of the project is defined.
    - name: IMAGE
      type: string
      default: "docker.io/node:16-alpine3.15"
      description: The node image you want to use.
  steps:
    - name: npm-build
      image: $(params.IMAGE)
      script: |
        npm install
        npm run build
      workingDir: $(workspaces.source.path)/$(params.PATH)
