apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-eventlistener
  namespace: cicd
spec:
  serviceAccountName: github-eventlistener
  triggers:
    - triggerRef: github-trigger-build
    - triggerRef: github-trigger-deploy
  resources:
    kubernetesResource:
      serviceType: LoadBalancer