apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: cicd
spec:
  params:
    - name: gitRepository
      value: $(body.repository.clone_url)
    - name: commits
      value: $(body.commits)