apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-eventlistener
  namespace: cicd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-eventlistener-binding
  namespace: cicd
subjects:
- kind: ServiceAccount
  name: github-eventlistener
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: github-eventlistener
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles